language: cpp
os:
  - linux
compiler:
  - clang
  - gcc
cache:
  apt: true
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - clang-3.6
      - libboost1.58-all-dev
before_script:
  - pwd
  - mkdir -p build/debug
  - cd build/debug
script:
  - cmake ../.. -DBUILD_TESTS=ON
  - make
  - make test
notifications:
  recepients:
    - sergei.a.fedorov@gmail.com
  email:
    on_success: change
    on_failure: always 
branches:
  except:
    - legacy
  
