language: cpp
os:
  - linux
compiler:
  - clang
  - gcc
cache:
  apt: true
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - libboost1.55-all-dev
      - libgtest-dev
before_install:
  - pwd
  - ls
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
before_script:
  - pwd
  - mkdir -p build/debug
  - cd build/debug
script:
  - cmake ../.. -DBUILD_TESTS=ON
  - make
  - make test
notifications:
  recepients:
    - sergei.a.fedorov@gmail.com
  email:
    on_success: change
    on_failure: always 
branches:
  except:
    - legacy
  
