language: cpp
os:
  - linux
compiler:
  - gcc
  - clang++
cache:
  apt: true
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - libboost1.55-all-dev
before_install:
  - pwd
  - ls
  - sudo apt-get update
  - sudo apt-get install libgtest-dev
  - "pushd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ && popd"
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.4; fi
  - $CXX -v
before_script:
  - pwd
  - mkdir -p build/debug
  - cd build/debug
script:
  - cmake ../.. -DBUILD_TESTS=ON
  - make
  - make test
notifications:
  recepients:
    - sergei.a.fedorov@gmail.com
  email:
    on_success: change
    on_failure: always 
branches:
  except:
    - legacy
  
